services:
  - type: web
    name: dsa-progress-tracker
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: dsa-tracker-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /
databases:
  - name: dsa-tracker-db
    databaseName: dsa_tracker
    user: dsa_user
    plan: free